/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-29 08:05:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.sistADD.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.RentCarDAO;
import java.util.HashMap;
import model.OfficeBean;
import java.util.List;

public final class office_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/github/RentCar/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MyBatisBasic_200521/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/github/RentCar/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MyBatisBasic_200521/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1590057700728L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.RentCarDAO");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("model.OfficeBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"wide wow-animation\" lang=\"en\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.5.0.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(function(){\r\n");
      out.write("\t\r\n");
      out.write("\t  $(\"input#all\").click(function(event){\t\t  \r\n");
      out.write("\t\t\t $(\"input[name='nt']\").each(function(){\t\t\t \r\n");
      out.write("\t\t\t\t $(this).prop(\"checked\",$(\"input#all\").is(\":checked\"));\t\t\t \r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t  });\t\r\n");
      out.write("\t\t  $(\"input[name='nt']\").click(function(){\r\n");
      out.write("\t\t\t  var state=false;\r\n");
      out.write("\t\t\t  $(\"input[name='nt']\").each(function(){\t//하나씩 체크 확인\t \r\n");
      out.write("\t\t\t\t  if(!$(this).prop(\"checked\")){\t\t\t//check되지 않으면 true\r\n");
      out.write("\t\t\t\t\t  state=true;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t  });//each\r\n");
      out.write("\t\t\t  $(\"input#all\").prop(\"checked\",(!state));   \r\n");
      out.write("\t\t  });\r\n");
      out.write("\r\n");
      out.write("\t\t  $(\"a#ckDel\").click(function(){\r\n");
      out.write("\t\t\t   var st=0;\r\n");
      out.write("\t\t\t $(\"input[name='nt']\").each(function(){\r\n");
      out.write("\t\t\t\tif($(this).is(\":checked\")){\r\n");
      out.write("\t\t\t\t\tst++;\r\n");
      out.write("\t\t\t\t}//if \r\n");
      out.write("\t\t\t });//each\r\n");
      out.write("\t\t\t if(st<=0){\r\n");
      out.write("\t\t\t\t alert('CheckBoxCheck');\r\n");
      out.write("\t\t\t\t return false;\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t $(\"form[name='delForm']\").submit();\r\n");
      out.write("\t\t  });\r\n");
      out.write("\r\n");
      out.write("\t\t  $(\"a[name='del']\").click(function(){\t\t//삭제버튼 클릭하면\r\n");
      out.write("\t\t\t  if($(this).text()=='DEL'){\t\t\t//'DEL'을 누르면\r\n");
      out.write("\t\t\t\talert('DEL버튼');\r\n");
      out.write("\t\t\t   location.reload();\t\t\t//새로고침 하는 명령어\r\n");
      out.write("\t\t\t  }  \t  \r\n");
      out.write("\t\t\t $(this).html(\"DEL\");\t\t\t//삭제버튼 text를 'DEL'로 바꿈\r\n");
      out.write("\t\t\t var delId=this.id;\r\n");
      out.write("\t\t\t $(\"input[type=checkbox]\").each(function(){\r\n");
      out.write("\t\t\t\t if(delId==this.id){\t\t\t \r\n");
      out.write("\t\t\t\t  $(this).prop(\"checked\",true);\r\n");
      out.write("\t\t\t\t  $(\"a[name='del']\").each(function(){\r\n");
      out.write("\t\t\t\t\t if(this.id!=del){\r\n");
      out.write("\t\t\t\t\t\t$(this).html(\"삭제\");\r\n");
      out.write("\t\t\t\t\t } \r\n");
      out.write("\t\t\t\t  });\r\n");
      out.write("\t\t\t\t }else{\r\n");
      out.write("\t\t\t\t\t $(this).prop(\"checked\",false);\r\n");
      out.write("\t\t\t\t }\t\t\t\r\n");
      out.write("\t\t\t });\r\n");
      out.write("\t\t  });\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Site Title-->\r\n");
      out.write("    <title>Admin var.SIST RENTCAR</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, height=device-height, initial-scale=1.0\">\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write(" \t<!---------------------- Stylesheets ------------------->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"//fonts.googleapis.com/css?family=Oswald:200,400%7CLato:300,400,300italic,700%7CMontserrat:900\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/fonts.css\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.com/css2?family=Nanum+Gothic+Coding&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\t<style>\r\n");
      out.write("\t.list{\r\n");
      out.write("\tmargin-left: 10px;\r\n");
      out.write("    margin-bottom: 46px;\r\n");
      out.write("    float: right;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  \r\n");
      out.write("  <body>\r\n");
      out.write("  ");

	String no= request.getParameter("nono");
  
  
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("   <form action=\"office.jsp\" name=\"delForm\" method=\"post\">    \r\n");
      out.write("    <!------------------ .page=전체 영역 ------------------->\r\n");
      out.write("    <div class=\"page\" id=\"page\">\r\n");
      out.write("      <!------------------ Header ------------------->\r\n");
      out.write("      <header class=\"section page-header\">\r\n");
      out.write("        <div class=\"rd-navbar-wrap rd-navbar-corporate\">\r\n");
      out.write("          <!----- 메뉴바 --------->\r\n");
      out.write("          <nav class=\"rd-navbar\"  id=\"menu\">\r\n");
      out.write("            <div class=\"rd-navbar-inner\">\r\n");
      out.write("              <!-- 모바일 var - 메뉴토글-->\r\n");
      out.write("              <div class=\"rd-navbar-panel\">\r\n");
      out.write("                <button class=\"rd-navbar-toggle\" data-rd-navbar-toggle=\".rd-navbar-nav-wrap\"><span></span></button>\r\n");
      out.write("                <!-- logo -->\r\n");
      out.write("                <div class=\"rd-navbar-brand\"><a class=\"brand-name\" href=\"../adminIndex.jsp\"><img class=\"logo-default\" src=\"../images/logo.png\" alt=\"\" width=\"208\" height=\"46\"/><img class=\"logo-inverse\" src=\"../images/logo-inverse-208x46.png\" alt=\"\" width=\"208\" height=\"46\"/></a></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 웹 var. 메뉴바 -->\r\n");
      out.write("              <div class=\"rd-navbar-aside-center\">\r\n");
      out.write("                <div class=\"rd-navbar-nav-wrap\">\r\n");
      out.write("                  <ul class=\"rd-navbar-nav\">\r\n");
      out.write("                  \t <li><a href=\"member.jsp\">회원관리</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">예약관리</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">지점관리</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">차량관리</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">게시판관리</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"#\">통계</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"rd-navbar-aside-right\">\r\n");
      out.write("              \t<p>[ADMIN]OOO님 환영합니다.</p>\r\n");
      out.write("              \t<a class=\"button button-sm button-secondary button-nina\" href=\"../index.jsp\">LOGOUT</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("     ");

     request.setCharacterEncoding("UTF-8");
     List<OfficeBean> list =null;
     list=RentCarDAO.selectOffice();
     
      out.write("\r\n");
      out.write("     <!------------------------------ 내용입력 ------------------------>\r\n");
      out.write("    <section class=\"section section-lg bg-gray-lighter novi-background bg-cover text-center\" id=\"reviews\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t  <div>\r\n");
      out.write("\t\t   <h2>지점 목록</h2>\r\n");
      out.write("\t\t\t   <a class=\"button button-sm button-secondary button-nina list\" href=\"#\">등록</a>\r\n");
      out.write("\t\t\t   <a class=\"button button-sm button-secondary button-nina list\" href=\"#\">수정</a>\r\n");
      out.write("\t\t\t   <!-- <a class=\"button button-sm button-secondary button-nina list\" id=\"ckDel\" >삭제</a> -->\r\n");
      out.write("\t\t\t   <a class=\"button button-sm button-secondary button-nina list\" name=\"del\" id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">삭제</a>\r\n");
      out.write("\t\t  </div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t <!--  <p>The .table-hover class enables a hover state on table rows:</p>    -->         \r\n");
      out.write("\t\t  <table class=\"table table-hover\">\r\n");
      out.write("\t\t    <thead>\r\n");
      out.write("\t\t      <tr>\r\n");
      out.write("\t\t        <th>지점번호</th>\r\n");
      out.write("\t\t        <th>지점명</th>\r\n");
      out.write("\t\t        <th>지점장</th>\r\n");
      out.write("\t\t        <th>지점장번호</th>\r\n");
      out.write("\t\t        <th>전화번호</th>\r\n");
      out.write("\t\t        <th>주소</th>\r\n");
      out.write("\t\t      </tr>\r\n");
      out.write("\t\t    </thead>\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    <tbody>\r\n");
      out.write("\t\t      ");
for (OfficeBean b: list){ 
      out.write("\r\n");
      out.write("\t\t    \t<tr lang=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${b.no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t    \t\t<td>\r\n");
      out.write("\t\t    \t\t<input type=\"checkbox\" id=\"");
      out.print(b.getOfcno() );
      out.write("\"  name=\"nt\" value=\"");
      out.print(b.getOfcno() );
      out.write("\" />\r\n");
      out.write("\t\t    \t\t");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cnt.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("<a id=\"nono\" name=\"nono\">");
      out.print(b.getOfcno() );
      out.write("</a>\r\n");
      out.write("\t\t    \t\t</td>\r\n");
      out.write("\t\t\t        <td>");
      out.print(b.getOfcname() );
      out.write("</td>\r\n");
      out.write("\t\t\t        <td>");
      out.print(b.getMgrname() );
      out.write("</td>\r\n");
      out.write("\t\t\t        <td>");
      out.print(b.getMemno() );
      out.write("</td>\r\n");
      out.write("\t\t\t        <td>");
      out.print(b.getOfctel() );
      out.write("</td>\r\n");
      out.write("\t\t\t        <td>");
      out.print(b.getOfcaddr() );
      out.write("</td>\r\n");
      out.write("\t\t      \t</tr>\r\n");
      out.write("\t\t      ");

		      }
		      
      out.write("\r\n");
      out.write("\t\t    </tbody>\r\n");
      out.write("\t\t  </table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</section>\r\n");
      out.write(" \r\n");
      out.write("      <!-------------------------- Footer ---------------------->\r\n");
      out.write("      <footer class=\"section page-footer page-footer-minimal novi-background bg-cover text-center bg-gray-darker\">\r\n");
      out.write("        <div class=\"container container-wide\">\r\n");
      out.write("          <div class=\"row row-fix justify-content-sm-center align-items-md-center row-30\">\r\n");
      out.write("            <div class=\"col-md-10 col-lg-7 col-xl-4 text-xl-left\"><a href=\"../adminIndex.jsp\"><img class=\"inverse-logo\" src=\"../images/logo-inverse-208x46.png\" alt=\"\" width=\"208\" height=\"46\"/></a></div>\r\n");
      out.write("            <div class=\"col-md-10 col-lg-7 col-xl-4\">\r\n");
      out.write("              <p class=\"right\">가시안이며 비상업적 취업지원 포트폴리오 용도로만 사용됩니다.<br/>오른쪽 이니셜 클릭시 개별 email로 연결됩니다.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-10 col-lg-7 col-xl-4 text-xl-right\">\r\n");
      out.write("              <ul class=\"group-xs group-middle\"> \r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">CHJ</a></li>\r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">PIC</a></li>\r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">YMM</a></li>\r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">CSH</a></li>\r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">LHJ</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Global Mailform Output-->\r\n");
      out.write("    <div class=\"snackbars\" id=\"form-output-global\"> </div>\r\n");
      out.write("    <!-- Javascript-->\r\n");
      out.write("    <script src=\"../js/core.min.js\"></script>\r\n");
      out.write("    <script src=\"../js/script.js\"></script>\r\n");
      out.write("    <!-- coded by barber-->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
