/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-05-21 11:27:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.SIST.sub;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class community_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/D:/github/RentCar/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MyBatisBasic_200521/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/D:/github/RentCar/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/MyBatisBasic_200521/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1590057700728L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html class=\"wide wow-animation\" lang=\"en\"> \r\n");
      out.write("  <head>\r\n");
      out.write("    <!-- Site Title-->\r\n");
      out.write("    <title>SIST RENTCAR</title>\r\n");
      out.write("<!--     <meta name=\"format-detection\" content=\"telephone=no\"> -->\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, height=device-height, initial-scale=1.0\">\r\n");
      out.write("<!--     <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write(" <!-- Stylesheets -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"//fonts.googleapis.com/css?family=Oswald:200,400%7CLato:300,400,300italic,700%7CMontserrat:900\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/fonts.css\">\r\n");
      out.write("\t<link href=\"https://fonts.googleapis.c\r\n");
      out.write("\tom/css2?family=Nanum+Gothic+Coding&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!-------------200521 페이징처리 css ----------------->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t.pagination {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  margin-top: 25px;\r\n");
      out.write("  padding-top: 10px;\r\n");
      out.write("  padding-bottom: 10px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul {\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  *display: inline;\r\n");
      out.write("  zoom: 1;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul li {\r\n");
      out.write("  float: left;\r\n");
      out.write("  width: 50px;\r\n");
      out.write("  height: 50px;\r\n");
      out.write("  margin-right: 5px;\r\n");
      out.write("  margin-left: 5px;\r\n");
      out.write("  line-height: 50px;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  opacity: 0.5;\r\n");
      out.write("  filter: alpha(opacity=50);\r\n");
      out.write("}\r\n");
      out.write(".pagination ul li.selected,\r\n");
      out.write(".pagination ul li:hover {\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("  color: #192028;\r\n");
      out.write("  -webkit-box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.1);\r\n");
      out.write("  font-weight: bold;\r\n");
      out.write("  color: #000;\r\n");
      out.write("  opacity: 1;\r\n");
      out.write("  filter: alpha(opacity=100);\r\n");
      out.write("}\r\n");
      out.write(".pagination ul a {\r\n");
      out.write("  display: block;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .first a,\r\n");
      out.write(".pagination ul .prev a,\r\n");
      out.write(".pagination ul .next a,\r\n");
      out.write(".pagination ul .last a {\r\n");
      out.write("  position: relative;\r\n");
      out.write("  color: transparent;\r\n");
      out.write("  text-shadow: none;\r\n");
      out.write("  text-indent: -9999px;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .first {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .first:before {\r\n");
      out.write("  content: '';\r\n");
      out.write("  background-image: url(\"/static/images/img-sprite.png\");\r\n");
      out.write("  background-position: 0 0;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  *display: inline;\r\n");
      out.write("  zoom: 1;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .first:before {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  margin: -6.5px 0 0 -6px;\r\n");
      out.write("  width: 12px;\r\n");
      out.write("  height: 13px;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .first:before {\r\n");
      out.write("  background-position: -270px -30px;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .prev {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .prev:before {\r\n");
      out.write("  content: '';\r\n");
      out.write("  background-image: url(\"/static/images/img-sprite.png\");\r\n");
      out.write("  background-position: 0 0;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  *display: inline;\r\n");
      out.write("  zoom: 1;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .prev:before {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  margin: -6.5px 0 0 -4px;\r\n");
      out.write("  width: 8px;\r\n");
      out.write("  height: 13px;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .prev:before {\r\n");
      out.write("  background-position: -50px -30px;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .next {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .next:before {\r\n");
      out.write("  content: '';\r\n");
      out.write("  background-image: url(\"/static/images/img-sprite.png\");\r\n");
      out.write("  background-position: 0 0;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  *display: inline;\r\n");
      out.write("  zoom: 1;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .next:before {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  margin: -6.5px 0 0 -4px;\r\n");
      out.write("  width: 8px;\r\n");
      out.write("  height: 13px;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .next:before {\r\n");
      out.write("  background-position: -60px -30px;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .last {\r\n");
      out.write("  position: relative;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .last:before {\r\n");
      out.write("  content: '';\r\n");
      out.write("  background-image: url(\"/static/images/img-sprite.png\");\r\n");
      out.write("  background-position: 0 0;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  *display: inline;\r\n");
      out.write("  zoom: 1;\r\n");
      out.write("  vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .last:before {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  top: 50%;\r\n");
      out.write("  left: 50%;\r\n");
      out.write("  margin: -6.5px 0 0 -6px;\r\n");
      out.write("  width: 12px;\r\n");
      out.write("  height: 13px;\r\n");
      out.write("}\r\n");
      out.write(".pagination ul .last:before {\r\n");
      out.write("  background-position: -290px -30px;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("</style>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!------------------ .page=전체 영역 ------------------->\r\n");
      out.write("    <div class=\"page\" id=\"page\">\r\n");
      out.write("      <!------------------ Header ------------------->\r\n");
      out.write("      <header class=\"section page-header\">\r\n");
      out.write("        <div class=\"rd-navbar-wrap rd-navbar-corporate\">\r\n");
      out.write("          <!----- 메뉴바 --------->\r\n");
      out.write("          <nav class=\"rd-navbar\"  id=\"menu\">\r\n");
      out.write("            <div class=\"rd-navbar-inner\">\r\n");
      out.write("              <!-- 모바일 var - 메뉴토글-->\r\n");
      out.write("              <div class=\"rd-navbar-panel\">\r\n");
      out.write("                <button class=\"rd-navbar-toggle\" data-rd-navbar-toggle=\".rd-navbar-nav-wrap\"><span></span></button>\r\n");
      out.write("                <!-- logo -->\r\n");
      out.write("                <div class=\"rd-navbar-brand\"><a class=\"brand-name\" href=\"../index.jsp\"><img class=\"logo-default\" src=\"../images/logo.png\" alt=\"\" width=\"208\" height=\"46\"/><img class=\"logo-inverse\" src=\"../images/logo-inverse-208x46.png\" alt=\"\" width=\"208\" height=\"46\"/></a></div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- 웹 var. 메뉴바 -->\r\n");
      out.write("              <div class=\"rd-navbar-aside-center\">\r\n");
      out.write("                <div class=\"rd-navbar-nav-wrap\">\r\n");
      out.write("                  <ul class=\"rd-navbar-nav\">\r\n");
      out.write("                    <li><a href=\"../index.jsp\">HOME</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"../index.jsp\">예약하기</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"../index.jsp\" class=\"active\">커뮤니티</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li><a href=\"review.jsp\">이용후기</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"rd-navbar-aside-right\">\r\n");
      out.write("              \t<a class=\"button button-sm button-secondary button-nina\" href=\"login.jsp\">Login</a>\r\n");
      out.write("              \t<a class=\"button button-sm button-secondary button-nina\" href=\"join.jsp\">Join</a>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("      </header>\r\n");
      out.write("\r\n");
      out.write("\t<!-----------------200521 추가내용 ------------------->\r\n");
      out.write("\t  <section>\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  <input type=\"hidden\" id=\"page\" name=\"page\" value=\"1\" />\r\n");
      out.write("<input type=\"hidden\" id=\"noticeSn\" name=\"noticeSn\" value=\"\" />\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"content-wrap\">\r\n");
      out.write("\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t<div class=\"left\">\r\n");
      out.write("            \t<div class=\"page-header\">\r\n");
      out.write("                    <h3 class=\"h3\">공지사항</h3>\r\n");
      out.write("                    <div class=\"form-search icon\">\r\n");
      out.write("                    \r\n");
      out.write("            \t\t\t<input type=\"text\" id=\"searchValue\" placeholder=\"검색어 입력\" name=\"searchValue\" value=\"\">\r\n");
      out.write("            \t\t\t<a class=\"button button-sm button-secondary button-nina\" href=\"#\">검색</a>\r\n");
      out.write("            \t\t\t<!-- <button type=\"button\" onclick=\"fncPage(1);\">검색</button> -->\r\n");
      out.write("                    <a class=\"button button-sm button-secondary button-nina\" href=\"#\">글쓰기</a>\r\n");
      out.write("                    <a class=\"button button-sm button-secondary button-nina\" href=\"#\">새로고침</a>\r\n");
      out.write("            \t\t\t\r\n");
      out.write("            \t\t\t\r\n");
      out.write("                    </div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"panel table table-stripe\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th scope=\"col\">번호</th>\r\n");
      out.write("                            <th scope=\"col\">제목</th>\r\n");
      out.write("                            <th scope=\"col\">작성자</th>\r\n");
      out.write("                            <th scope=\"col\">작성일</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    \t<tr>\r\n");
      out.write("                            <th scope=\"col\">1</th>\r\n");
      out.write("                            <th scope=\"col\">문의합니다</th>\r\n");
      out.write("                            <th scope=\"col\">최서현</th>\r\n");
      out.write("                            <th scope=\"col\">2020-05-18</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("  \r\n");
      out.write("                    </tbody>\r\n");
      out.write("  </table>\r\n");
      out.write("  \r\n");
      out.write("  \t  <div class=\"pagination\">\r\n");
      out.write("\t\t <ul>\r\n");
      out.write("\t\t\t<li class=\"selected\">1</li>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<li><a href=\"#\">2</a></li> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<li><a href=\"#\">3</a></li> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<li><a href=\"#\">4</a></li> \r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<li><a href=\"#\">5</a></li> \r\n");
      out.write("\r\n");
      out.write("\t\t</ui>\t\t\r\n");
      out.write("     </div><!--//pagination-->\r\n");
      out.write("      \t\r\n");
      out.write("\t\t</div><!--//left-->\r\n");
      out.write("\t\t</div><!--//content-->\r\n");
      out.write("    </div><!--//content-wrap-->\r\n");
      out.write("</div><!--//container-->\r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  \r\n");
      out.write("\t  </section>\r\n");
      out.write("\r\n");
      out.write("      <!-------------------------- Footer ---------------------->\r\n");
      out.write("      <footer class=\"section page-footer page-footer-minimal novi-background bg-cover text-center bg-gray-darker\">\r\n");
      out.write("        <div class=\"container container-wide\">\r\n");
      out.write("          <div class=\"row row-fix justify-content-sm-center align-items-md-center row-30\">\r\n");
      out.write("            <div class=\"col-md-10 col-lg-7 col-xl-4 text-xl-left\"><a href=\"index.html\"><img class=\"inverse-logo\" src=\"../images/logo-inverse-208x46.png\" alt=\"\" width=\"208\" height=\"46\"/></a></div>\r\n");
      out.write("            <div class=\"col-md-10 col-lg-7 col-xl-4\">\r\n");
      out.write("              <p class=\"right\">가시안이며 비상업적 취업지원 포트폴리오 용도로만 사용됩니다.<br/></p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-10 col-lg-7 col-xl-4 text-xl-right\">\r\n");
      out.write("              <ul class=\"group-xs group-middle\"> \r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">CHJ</a></li>\r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">PIC</a></li>\r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">YMM</a></li>\r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">CSH</a></li>\r\n");
      out.write("                <li><a class=\"icon novi-icon icon-md-middle icon-circle icon-secondary-5-filled mdi\" href=\"#\">LHJ</a></li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Global Mailform Output-->\r\n");
      out.write("    <div class=\"snackbars\" id=\"form-output-global\"> </div>\r\n");
      out.write("    <!-- Javascript-->\r\n");
      out.write("    <script src=\"../js/core.min.js\"></script>\r\n");
      out.write("    <script src=\"../js/script.js\"></script>\r\n");
      out.write("    <!-- coded by barber-->\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
